version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin12345
      POSTGRES_DB: study
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  
    